plugins {
    id 'java'
}

// Указываем версию плагина (замените на свою, например 1.0.0)
version = '1.0.0'

compileJava.options.encoding = 'UTF-8'

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

repositories {
    mavenCentral()
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://jitpack.io' }
    maven { url 'https://repo.skriptlang.org/releases' }
    maven { url 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
}

dependencies {
    implementation group: 'org.jetbrains', name: 'annotations', version: '24.1.0'
    implementation 'org.spigotmc:spigot-api:1.19.4-R0.1-SNAPSHOT'
    implementation('com.github.SkriptLang:Skript:2.10.2') {
        transitive = false
    }
}

processResources {
    def tokens = [
            'version': project.version,
            'name': 'skript-placeholders'
    ]
    filesMatching('**/*') {
        filter { line ->
            tokens.inject(line) { l, token, value ->
                l.replace("@$token@", value)
            }
        }
    }
}

tasks.register('nightlyResources', ProcessResources) {
    from 'src/main/resources' {
        include '**'
        filter { line ->
            line.replace('@version@', project.version + '-nightly-' + 'git rev-parse --short HEAD'.execute().text.trim())
        }
    }
    into 'build/resources/main'
}

tasks.register('nightlyBuild', Jar) {
    dependsOn nightlyResources
    from sourceSets.main.output
    archiveFileName = 'skript-placeholders-nightly.jar'
}